name: github_trending
description: A library to get GitHub trending repositories, with languages and period options.
version: 0.1.0
homepage: https://github.com/pd4d10/github-trending
author: Rongjian Zhang <pd4d10@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  html: ^0.13.3

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
