name: github_trending
description: A library to get GitHub trending repositories and developers, with languages and period options.
version: 0.1.2
homepage: https://github.com/pd4d10/github-trending
author: Rongjian Zhang <pd4d10@gmail.com>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  http: ^0.12.0
  json_annotation: ^3.0.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.7.4
  json_serializable: ^3.2.5
